import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["AGENTHORSY_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["AGENTHORSY_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("AGENTHORSY_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  AGENTHORSY_AUTO_HEAP_SNAPSHOT: truthy("AGENTHORSY_AUTO_HEAP_SNAPSHOT"),
  AGENTHORSY_GIT_BASH_PATH: process.env["AGENTHORSY_GIT_BASH_PATH"],
  AGENTHORSY_CONFIG: process.env["AGENTHORSY_CONFIG"],
  AGENTHORSY_CONFIG_CONTENT: process.env["AGENTHORSY_CONFIG_CONTENT"],
  AGENTHORSY_DISABLE_AUTOUPDATE: truthy("AGENTHORSY_DISABLE_AUTOUPDATE"),
  AGENTHORSY_ALWAYS_NOTIFY_UPDATE: truthy("AGENTHORSY_ALWAYS_NOTIFY_UPDATE"),
  AGENTHORSY_DISABLE_PRUNE: truthy("AGENTHORSY_DISABLE_PRUNE"),
  AGENTHORSY_DISABLE_TERMINAL_TITLE: truthy("AGENTHORSY_DISABLE_TERMINAL_TITLE"),
  AGENTHORSY_SHOW_TTFD: truthy("AGENTHORSY_SHOW_TTFD"),
  AGENTHORSY_DISABLE_AUTOCOMPACT: truthy("AGENTHORSY_DISABLE_AUTOCOMPACT"),
  AGENTHORSY_DISABLE_MODELS_FETCH: truthy("AGENTHORSY_DISABLE_MODELS_FETCH"),
  AGENTHORSY_DISABLE_MOUSE: truthy("AGENTHORSY_DISABLE_MOUSE"),
  AGENTHORSY_FAKE_VCS: process.env["AGENTHORSY_FAKE_VCS"],
  AGENTHORSY_SERVER_PASSWORD: process.env["AGENTHORSY_SERVER_PASSWORD"],
  AGENTHORSY_SERVER_USERNAME: process.env["AGENTHORSY_SERVER_USERNAME"],
  AGENTHORSY_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("AGENTHORSY_DISABLE_FFF"),

  // Experimental
  AGENTHORSY_EXPERIMENTAL_FILEWATCHER: Config.boolean("AGENTHORSY_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  AGENTHORSY_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("AGENTHORSY_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  AGENTHORSY_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("AGENTHORSY_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  AGENTHORSY_MODELS_URL: process.env["AGENTHORSY_MODELS_URL"],
  AGENTHORSY_MODELS_PATH: process.env["AGENTHORSY_MODELS_PATH"],
  AGENTHORSY_DB: process.env["AGENTHORSY_DB"],

  AGENTHORSY_WORKSPACE_ID: process.env["AGENTHORSY_WORKSPACE_ID"],
  AGENTHORSY_EXPERIMENTAL_WORKSPACES: enabledByExperimental("AGENTHORSY_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get AGENTHORSY_DISABLE_PROJECT_CONFIG() {
    return truthy("AGENTHORSY_DISABLE_PROJECT_CONFIG")
  },
  get AGENTHORSY_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("AGENTHORSY_EXPERIMENTAL_REFERENCES")
  },
  get AGENTHORSY_TUI_CONFIG() {
    return process.env["AGENTHORSY_TUI_CONFIG"]
  },
  get AGENTHORSY_CONFIG_DIR() {
    return process.env["AGENTHORSY_CONFIG_DIR"]
  },
  get AGENTHORSY_PURE() {
    return truthy("AGENTHORSY_PURE")
  },
  get AGENTHORSY_PERMISSION() {
    return process.env["AGENTHORSY_PERMISSION"]
  },
  get AGENTHORSY_PLUGIN_META_FILE() {
    return process.env["AGENTHORSY_PLUGIN_META_FILE"]
  },
  get AGENTHORSY_CLIENT() {
    return process.env["AGENTHORSY_CLIENT"] ?? "cli"
  },
}
